### ISSUE TITLE
HaeinsaResult.getValue return null when using the API without HaeinsaTransaction

### ISSUE THREAD

**Issue by ehudl** [VCNC/haeinsa#37]
When running read without HaeinsaTransaction. 
We can see that we get the values in the HaeinsaResult, but I can use the getValue api nor the containsColumn (since it is using the getValue). 
Is this a bug ? 

In order to work around this I use list and matching the value by (family, qualifier) with my own code.

**Comment by eincs** [comment]
Yes it was bug, I fixed it on pull request #38. In the pull request, you can see what was problem. I will release fixed version after it merged. Thanks for reporting bug.

**Comment by eincs** [comment]
@ehudl I uploaded fixed version (v1.0.5) to maven central. I think it is visible for public now:
http://repo1.maven.org/maven2/kr/co/vcnc/haeinsa/haeinsa/1.0.5/

Fix your version of haeinsa dependency:

	<dependency>
	    <groupId>kr.co.vcnc.haeinsa</groupId>
	    <artifactId>haeinsa</artifactId>
	    <version>1.0.5</version>
	</dependency>

**Comment by ehudl** [comment]
Thank you
